-- Create sequences section -------------------------------------------------

CREATE SEQUENCE "CITY_SEQ"
	INCREMENT BY 1
	MINVALUE -1
	MAXVALUE 9999999999999999999999999999
	START WITH 0;

CREATE SEQUENCE "CLIENT_SEQ"
	INCREMENT BY 1
	MINVALUE -1
	MAXVALUE 9999999999999999999999999999
	START WITH 0;

CREATE SEQUENCE "CONTRACT_SEQ"
	INCREMENT BY 1
	MINVALUE -1
	MAXVALUE 9999999999999999999999999999
	START WITH 0;

CREATE SEQUENCE "COUNTRY_SEQ"
	INCREMENT BY 1
	MINVALUE -1
	MAXVALUE 9999999999999999999999999999
	START WITH 0;

CREATE SEQUENCE "COURSE_SEQ"
	INCREMENT BY 1
	MINVALUE -1
	MAXVALUE 9999999999999999999999999999
	START WITH 0;

CREATE SEQUENCE "EMPLOYMENT_CONTRACT_SEQ"
	INCREMENT BY 1
	MINVALUE -1
	MAXVALUE 9999999999999999999999999999
	START WITH 0;

CREATE SEQUENCE "INTEREST_SEQ"
	INCREMENT BY 1
	MINVALUE -1
	MAXVALUE 9999999999999999999999999999
	START WITH 0;

CREATE SEQUENCE "PROJECT_SEQ"
	INCREMENT BY 1
	MINVALUE -1
	MAXVALUE 9999999999999999999999999999
	START WITH 0;

CREATE SEQUENCE "SERVICE_SEQ"
	INCREMENT BY 1
	MINVALUE -1
	MAXVALUE 9999999999999999999999999999
	START WITH 0;

CREATE SEQUENCE "SKILL_SEQ"
	INCREMENT BY 1
	MINVALUE -1
	MAXVALUE 9999999999999999999999999999
	START WITH 0;

CREATE SEQUENCE "STAFF_SEQ"
	INCREMENT BY 1
	MINVALUE -1
	MAXVALUE 9999999999999999999999999999
	START WITH 0;

CREATE SEQUENCE "SUPPLIER_SEQ"
	INCREMENT BY 1
	MINVALUE -1
	MAXVALUE 9999999999999999999999999999
	START WITH 0;

CREATE SEQUENCE "TASK_SEQ"
	INCREMENT BY 1
	MINVALUE -1
	MAXVALUE 9999999999999999999999999999
	START WITH 0;

-- Create tables section -------------------------------------------------

CREATE TABLE "AGREEMENT" (
		"CLIENT_ID" NUMBER(38 , 0) NOT NULL,
		"CONTRACT_ID" NUMBER(38 , 0) NOT NULL,
		"SERVICE_ID" NUMBER(38 , 0) NOT NULL
	);

CREATE TABLE "ASSIGNMENT" (
		"TASK_ID" NUMBER(38 , 0) NOT NULL,
		"PROJECT_ID" NUMBER(38 , 0) NOT NULL,
		"CLIENT_ID" NUMBER(38 , 0) NOT NULL,
		"STAFF_ID" NUMBER(38 , 0) NOT NULL
	);

CREATE TABLE "CITY" (
		"CITY_ID" NUMBER(38 , 0) NOT NULL,
		"COUNTRY_ID" NUMBER(38 , 0) NOT NULL,
		"NAME" VARCHAR2(30) NOT NULL
	);

CREATE TABLE "CLIENT" (
		"CLIENT_ID" NUMBER(38 , 0) NOT NULL,
		"NAME" VARCHAR2(50) NOT NULL,
		"WEBSITE" VARCHAR2(100)
	);

CREATE TABLE "CONTRACT" (
		"CONTRACT_ID" NUMBER(38 , 0) NOT NULL,
		"CLIENT_ID" NUMBER(38 , 0) NOT NULL,
		"NAME" VARCHAR2(30) NOT NULL
	);

CREATE TABLE "COUNTRY" (
		"COUNTRY_ID" NUMBER(38 , 0) NOT NULL,
		"NAME" VARCHAR2(30) NOT NULL
	);

CREATE TABLE "COURSE" (
		"COURSE_ID" NUMBER(38 , 0) NOT NULL,
		"TITLE" VARCHAR2(100) NOT NULL,
		"CREDITS" NUMBER(38 , 0)
	);

CREATE TABLE "EMPLOYMENT_CONTRACT" (
		"EMPLOYMENT_CONTRACT_ID" NUMBER(38 , 0) NOT NULL,
		"STAFF_ID" NUMBER(38 , 0) NOT NULL,
		"SUPPLIER_ID" NUMBER(38 , 0) NOT NULL,
		"START_DATE" DATE NOT NULL,
		"END_DATE" DATE
	);

CREATE TABLE "ENROLMENT" (
		"COURSE_ID" NUMBER(38 , 0) NOT NULL,
		"STAFF_ID" NUMBER(38 , 0) NOT NULL,
		"GRADE" VARCHAR2(30),
		"START_DATE" DATE,
		"END_DATE" DATE,
		"DURATION" NUMBER(38 , 0)
	);

CREATE TABLE "INTEREST" (
		"INTEREST_ID" NUMBER(38 , 0) NOT NULL,
		"STAFF_ID" NUMBER(38 , 0),
		"DESC" VARCHAR2(500)
	);

CREATE TABLE "LOCATION" (
		"PROJECT_ID" NUMBER(38 , 0) NOT NULL,
		"CLIENT_ID" NUMBER(38 , 0) NOT NULL,
		"CITY_ID" NUMBER(38 , 0) NOT NULL,
		"COUNTRY_ID" NUMBER(38 , 0) NOT NULL
	);

CREATE TABLE "PROJECT" (
		"PROJECT_ID" NUMBER(38 , 0) NOT NULL,
		"NAME" VARCHAR2(30) NOT NULL,
		"VERSION" VARCHAR2(30) NOT NULL,
		"CLIENT_ID" NUMBER(38 , 0) NOT NULL,
		"DESC" VARCHAR2(400)
	);

CREATE TABLE "SERVICE" (
		"SERVICE_ID" NUMBER(38 , 0) NOT NULL,
		"NAME" VARCHAR2(50) NOT NULL,
		"DESC" VARCHAR2(400)
	);

CREATE TABLE "SKILL" (
		"SKILL_ID" NUMBER(38 , 0) NOT NULL,
		"NAME" VARCHAR2(30) NOT NULL
	);

CREATE TABLE "STAFF" (
		"STAFF_ID" NUMBER(38 , 0) NOT NULL,
		"FIRSTNAME" VARCHAR2(30) NOT NULL,
		"LASTNAME" VARCHAR2(30) NOT NULL,
		"BIRTH_DATE" DATE NOT NULL
	);

CREATE TABLE "STAFF_SKILL" (
		"STAFF_ID" NUMBER(38 , 0) NOT NULL,
		"SKILL_ID" NUMBER(38 , 0) NOT NULL,
		"YEARS_OF_EXPERIENCE" NUMBER(38 , 0),
		"ENDORSEMENT" NUMBER(38 , 0)
	);

CREATE TABLE "SUPPLIER" (
		"SUPPLIER_ID" NUMBER(38 , 0) NOT NULL,
		"NAME" VARCHAR2(30) NOT NULL
	);

CREATE TABLE "SUPPLY_CONTRACT" (
		"SUPPLIER_ID" NUMBER(38 , 0) NOT NULL,
		"CLIENT_ID" NUMBER(38 , 0) NOT NULL,
		"CONTRACT_ID" NUMBER(38 , 0) NOT NULL,
		"STAFF_ID" NUMBER(38 , 0) NOT NULL,
		"START_DATE" DATE NOT NULL,
		"END_DATE" DATE
	);

CREATE TABLE "TASK" (
		"TASK_ID" NUMBER(38 , 0) NOT NULL,
		"DESC" VARCHAR2(255) NOT NULL,
		"PRIORITY" NUMBER(38 , 0)
	);
	
-- Create keys --

ALTER TABLE "AGREEMENT" ADD CONSTRAINT "AGREEMENT_PK" PRIMARY KEY ("CLIENT_ID",	 "CONTRACT_ID",	 "SERVICE_ID"); 
ALTER TABLE "ASSIGNMENT" ADD CONSTRAINT "ASSIGNMENT_PK" PRIMARY KEY	("TASK_ID",	 "PROJECT_ID", "STAFF_ID", "CLIENT_ID");
ALTER TABLE "CITY" ADD CONSTRAINT "CITY_AK" UNIQUE	("NAME");
ALTER TABLE "CITY" ADD CONSTRAINT "CITY_PK" PRIMARY KEY ("CITY_ID", "COUNTRY_ID");
ALTER TABLE "CLIENT" ADD CONSTRAINT "CLIENT_AK" UNIQUE ("NAME");
ALTER TABLE "CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY	("CLIENT_ID");
ALTER TABLE "CONTRACT" ADD CONSTRAINT "CONTRACT_AK" UNIQUE ("NAME");
ALTER TABLE "CONTRACT" ADD CONSTRAINT "CONTRACT_PK" PRIMARY KEY	("CLIENT_ID", "CONTRACT_ID");
ALTER TABLE "COUNTRY" ADD CONSTRAINT "COUNTRY_AK" UNIQUE ("NAME");
ALTER TABLE "COUNTRY" ADD CONSTRAINT "COUNTRY_PK" PRIMARY KEY ("COUNTRY_ID");
ALTER TABLE "COURSE" ADD CONSTRAINT "COURSE_AK" UNIQUE ("TITLE");
ALTER TABLE "COURSE" ADD CONSTRAINT "COURSE_PK" PRIMARY KEY ("COURSE_ID");
ALTER TABLE "EMPLOYMENT_CONTRACT" ADD CONSTRAINT "EMPLOYMENT_CONTRACT_PK" PRIMARY KEY ("EMPLOYMENT_CONTRACT_ID", "STAFF_ID", "SUPPLIER_ID");
ALTER TABLE "ENROLMENT" ADD CONSTRAINT "ENROLMENT_PK" PRIMARY KEY ("COURSE_ID", "STAFF_ID");
ALTER TABLE "INTEREST" ADD CONSTRAINT "INTEREST_PK" PRIMARY KEY	("INTEREST_ID");
ALTER TABLE "LOCATION" ADD CONSTRAINT "LOCATION_PK" PRIMARY KEY	("CLIENT_ID",  "CITY_ID", "COUNTRY_ID", "PROJECT_ID");
ALTER TABLE "PROJECT" ADD CONSTRAINT "PROJECT_AK" UNIQUE ("NAME", "VERSION");
ALTER TABLE "PROJECT" ADD CONSTRAINT "PROJECT_PK" PRIMARY KEY ("CLIENT_ID", "PROJECT_ID");
ALTER TABLE "SERVICE" ADD CONSTRAINT "SERVICE_AK" UNIQUE ("NAME");
ALTER TABLE "SERVICE" ADD CONSTRAINT "SERVICE_PK" PRIMARY KEY ("SERVICE_ID");
ALTER TABLE "SKILL" ADD CONSTRAINT "SKILL_AK" UNIQUE ("NAME");
ALTER TABLE "SKILL" ADD CONSTRAINT "SKILL_PK" PRIMARY KEY ("SKILL_ID");
ALTER TABLE "STAFF" ADD CONSTRAINT "STAFF_AK" UNIQUE ("FIRSTNAME", "LASTNAME", "BIRTH_DATE");
ALTER TABLE "STAFF" ADD CONSTRAINT "STAFF_PK" PRIMARY KEY ("STAFF_ID");
ALTER TABLE "STAFF_SKILL" ADD CONSTRAINT "STAFF SKILL_PK" PRIMARY KEY ("STAFF_ID", "SKILL_ID");
ALTER TABLE "SUPPLIER" ADD CONSTRAINT "SUPPLIER_AK" UNIQUE	("NAME");
ALTER TABLE "SUPPLIER" ADD CONSTRAINT "SUPPLIER_PK" PRIMARY KEY ("SUPPLIER_ID");
ALTER TABLE "SUPPLY_CONTRACT" ADD CONSTRAINT "SUPPLY_CONTRACT_PK" PRIMARY KEY ("SUPPLIER_ID","CLIENT_ID","CONTRACT_ID",	 "STAFF_ID");
ALTER TABLE "TASK" ADD CONSTRAINT "TASK_PK" PRIMARY KEY	("TASK_ID");
ALTER TABLE "TASK" ADD CONSTRAINT "TASK_AK" UNIQUE ("DESC");

-- Create foreign keys (relationships) section ------------------------------------------------- 

ALTER TABLE "AGREEMENT" ADD CONSTRAINT "ENGAGES" FOREIGN KEY ("CLIENT_ID", "CONTRACT_ID") REFERENCES "CONTRACT"	("CLIENT_ID", "CONTRACT_ID") ON DELETE CASCADE;
ALTER TABLE "AGREEMENT" ADD CONSTRAINT "PROVIDES" FOREIGN KEY ("SERVICE_ID") REFERENCES "SERVICE" ("SERVICE_ID") ON DELETE CASCADE;
ALTER TABLE "ASSIGNMENT" ADD CONSTRAINT "EXECUTES" FOREIGN KEY ("TASK_ID") REFERENCES "TASK" ("TASK_ID");
ALTER TABLE "ASSIGNMENT" ADD CONSTRAINT "IS COMPOSED OF" FOREIGN KEY ("CLIENT_ID", "PROJECT_ID") REFERENCES "PROJECT" ("CLIENT_ID",	"PROJECT_ID");
ALTER TABLE "ASSIGNMENT" ADD CONSTRAINT "WORKS ON" FOREIGN KEY ("STAFF_ID")	REFERENCES "STAFF" ("STAFF_ID");
ALTER TABLE "CITY" ADD CONSTRAINT "HAS A" FOREIGN KEY ("COUNTRY_ID") REFERENCES "COUNTRY" ("COUNTRY_ID");
ALTER TABLE "CONTRACT" ADD CONSTRAINT "SIGNS" FOREIGN KEY ("CLIENT_ID") REFERENCES "CLIENT" ("CLIENT_ID");
ALTER TABLE "EMPLOYMENT_CONTRACT" ADD CONSTRAINT "EMPLOYS" FOREIGN KEY ("SUPPLIER_ID") REFERENCES "SUPPLIER" ("SUPPLIER_ID") ON DELETE CASCADE;
ALTER TABLE "EMPLOYMENT_CONTRACT" ADD CONSTRAINT "IS EMPLOYED" FOREIGN KEY ("STAFF_ID") REFERENCES "STAFF" ("STAFF_ID") ON DELETE CASCADE;
ALTER TABLE "ENROLMENT" ADD CONSTRAINT "ENROLS" FOREIGN KEY ("STAFF_ID") REFERENCES "STAFF" ("STAFF_ID") ON DELETE CASCADE;
ALTER TABLE "ENROLMENT" ADD CONSTRAINT "IN" FOREIGN KEY ("COURSE_ID") REFERENCES "COURSE" ("COURSE_ID") ON DELETE CASCADE;
ALTER TABLE "INTEREST" ADD CONSTRAINT "HAS" FOREIGN KEY ("STAFF_ID") REFERENCES "STAFF" ("STAFF_ID") ON DELETE CASCADE;
ALTER TABLE "LOCATION" ADD CONSTRAINT "ESTABLISHES A" FOREIGN KEY ("CITY_ID", "COUNTRY_ID") REFERENCES "CITY" ("CITY_ID", "COUNTRY_ID") ON DELETE CASCADE;
ALTER TABLE "LOCATION" ADD CONSTRAINT "IS BASED" FOREIGN KEY ("CLIENT_ID", "PROJECT_ID") REFERENCES "PROJECT" ("CLIENT_ID", "PROJECT_ID") ON DELETE CASCADE;
ALTER TABLE "PROJECT" ADD CONSTRAINT "CONTROLS" FOREIGN KEY ("CLIENT_ID") REFERENCES "CLIENT" ("CLIENT_ID"); 
ALTER TABLE "STAFF_SKILL" ADD CONSTRAINT "IS USED" FOREIGN KEY ("SKILL_ID") REFERENCES "SKILL" ("SKILL_ID") ON DELETE CASCADE;
ALTER TABLE "STAFF_SKILL" ADD CONSTRAINT "USES" FOREIGN KEY ("STAFF_ID") REFERENCES "STAFF" ("STAFF_ID") ON DELETE CASCADE;
ALTER TABLE "SUPPLY_CONTRACT" ADD CONSTRAINT "AGREES" FOREIGN KEY ("SUPPLIER_ID") REFERENCES "SUPPLIER" ("SUPPLIER_ID") ON DELETE CASCADE;
ALTER TABLE "SUPPLY_CONTRACT" ADD CONSTRAINT "COMMITS TO" FOREIGN KEY ("CLIENT_ID", "CONTRACT_ID") REFERENCES "CONTRACT" ("CLIENT_ID", "CONTRACT_ID") ON DELETE CASCADE;
ALTER TABLE "SUPPLY_CONTRACT" ADD CONSTRAINT "WORKS IN" FOREIGN KEY ("STAFF_ID") REFERENCES "STAFF" ("STAFF_ID") ON DELETE CASCADE;
COMMIT;