-- Create views section -------------------------------------------------

CREATE OR REPLACE VIEW "v_ProjectTask" ("PROJECT_ID", "VERSION", "FIRSTNAME", "LASTNAME", "PROJECT", "PROJECT_VERSION", "TASK") AS
SELECT "PROJECT"."PROJECT_ID", "VERSION", "FIRSTNAME", "LASTNAME", "NAME" AS "PROJECT", "VERSION" AS "PROJECT_VERSION", "TASK"."DESC" AS "TASK"
FROM "ASSIGNMENT", "PROJECT", "STAFF", "TASK"
WHERE PROJECT.PROJECT_ID = ASSIGNMENT.PROJECT_ID AND
PROJECT.CLIENT_ID = ASSIGNMENT.CLIENT_ID AND
ASSIGNMENT.TASK_ID = TASK.TASK_ID AND
STAFF.STAFF_ID = ASSIGNMENT.STAFF_ID
ORDER BY PROJECT.NAME;


CREATE OR REPLACE VIEW "v_Experience" ("CONTRACT_ID", "FIRSTNAME", "LASTNAME", "ROLE", "CUSTOMER", "CITY", "COUNTRY") AS
SELECT "CONTRACT"."CONTRACT_ID", "FIRSTNAME", "LASTNAME", "SERVICE"."NAME" AS "ROLE", "CLIENT"."NAME" AS "CUSTOMER", "CITY"."NAME" AS "CITY", "COUNTRY"."NAME" AS "COUNTRY"
FROM "SERVICE", "CLIENT", "CONTRACT", "STAFF", "PROJECT", "COUNTRY", "CITY", "LOCATION", "ASSIGNMENT", "SUPPLIER", "AGREEMENT", "EMPLOYMENT_CONTRACT", "SUPPLY_CONTRACT"
WHERE CITY.COUNTRY_ID = COUNTRY.COUNTRY_ID AND
LOCATION.CITY_ID = CITY.CITY_ID AND 
LOCATION.COUNTRY_ID = CITY.COUNTRY_ID AND 
LOCATION.PROJECT_ID = PROJECT.PROJECT_ID AND
PROJECT.CLIENT_ID = CLIENT.CLIENT_ID AND
CLIENT.CLIENT_ID = CONTRACT.CLIENT_ID AND
PROJECT.PROJECT_ID = ASSIGNMENT.PROJECT_ID AND
PROJECT.CLIENT_ID = ASSIGNMENT.CLIENT_ID AND
ASSIGNMENT.STAFF_ID = STAFF.STAFF_ID AND
CONTRACT.CONTRACT_ID = AGREEMENT.CONTRACT_ID AND
CONTRACT.CLIENT_ID  = AGREEMENT.CLIENT_ID AND
AGREEMENT.SERVICE_ID = SERVICE.SERVICE_ID  AND
CONTRACT.CONTRACT_ID = SUPPLY_CONTRACT.CONTRACT_ID AND
CONTRACT.CLIENT_ID = SUPPLY_CONTRACT.CLIENT_ID AND
SUPPLIER.SUPPLIER_ID = SUPPLY_CONTRACT.SUPPLIER_ID AND
SUPPLIER.SUPPLIER_ID = EMPLOYMENT_CONTRACT.SUPPLIER_ID AND
EMPLOYMENT_CONTRACT.STAFF_ID = STAFF.STAFF_ID
GROUP BY "CONTRACT"."CONTRACT_ID", "FIRSTNAME", "LASTNAME", "SERVICE"."NAME", "CLIENT"."NAME", "CITY"."NAME", "COUNTRY"."NAME";

CREATE OR REPLACE VIEW "v_Resume" ("CONTRACT_ID", "CONTRACT", "FIRSTNAME", "LASTNAME", "ROLE", "CUSTOMER", "SUPPLIER", "CITY", "COUNTRY", "PROJECT", "TASK", "START_DATE", "END_DATE") AS
SELECT "CONTRACT"."CONTRACT_ID", "CONTRACT"."NAME" AS "CONTRACT", "FIRSTNAME", "LASTNAME", "SERVICE"."NAME" AS "ROLE", "CLIENT"."NAME" AS "CUSTOMER", "SUPPLIER"."NAME" AS "SUPPLIER", "CITY"."NAME" AS "CITY", "COUNTRY"."NAME" AS "COUNTRY", "PROJECT"."NAME" AS "PROJECT", "TASK"."DESC" AS "TASK", "START_DATE", "END_DATE"
FROM "CLIENT", "COUNTRY", "PROJECT", "CONTRACT", "ASSIGNMENT", "SERVICE", "STAFF", "CITY", "SUPPLIER", "LOCATION", "TASK", "AGREEMENT", "SUPPLY_CONTRACT"
WHERE CITY.COUNTRY_ID                         = COUNTRY.COUNTRY_ID AND
LOCATION.CITY_ID                        = CITY.CITY_ID AND 
LOCATION.COUNTRY_ID                     = CITY.COUNTRY_ID AND 
LOCATION.PROJECT_ID                     = PROJECT.PROJECT_ID AND
PROJECT.CLIENT_ID                       = CLIENT.CLIENT_ID AND
CLIENT.CLIENT_ID                        = CONTRACT.CLIENT_ID AND
PROJECT.PROJECT_ID                      = ASSIGNMENT.PROJECT_ID AND
PROJECT.CLIENT_ID                       = ASSIGNMENT.CLIENT_ID AND
ASSIGNMENT.STAFF_ID       				= STAFF.STAFF_ID AND
CONTRACT.CONTRACT_ID                    = AGREEMENT.CONTRACT_ID AND
CONTRACT.CLIENT_ID                      = AGREEMENT.CLIENT_ID AND
AGREEMENT.SERVICE_ID   					= SERVICE.SERVICE_ID  AND
CONTRACT.CONTRACT_ID                    = SUPPLY_CONTRACT.CONTRACT_ID AND
CONTRACT.CLIENT_ID                      = SUPPLY_CONTRACT.CLIENT_ID AND
SUPPLIER.SUPPLIER_ID                    = SUPPLY_CONTRACT.SUPPLIER_ID AND
STAFF.STAFF_ID                          = SUPPLY_CONTRACT.STAFF_ID AND
TASK.TASK_ID               				 = ASSIGNMENT.TASK_ID
GROUP BY "CONTRACT"."CONTRACT_ID", "CONTRACT"."NAME", "FIRSTNAME", "LASTNAME", "SERVICE"."NAME", "CLIENT"."NAME", "CITY"."NAME", "COUNTRY"."NAME", "PROJECT"."NAME", "TASK"."DESC", "SUPPLIER"."NAME", "START_DATE", "END_DATE";

COMMIT;