-- Create views section -------------------------------------------------

CREATE VIEW "v_ProjectTask" AS
SELECT "PROJECT"."PROJECT_ID", "VERSION", "FIRSTNAME", "LASTNAME", "NAME" AS "PROJECT", "VERSION" AS "PROJECT_VERSION", "ASSIGNMENT"."DESC" AS "TASK"
FROM "STAFF_PROJECT_ASSIGNMENT", "PROJECT", "STAFF", "ASSIGNMENT"
WHERE PROJECT.PROJECT_ID = STAFF_PROJECT_ASSIGNMENT.PROJECT_ID AND
PROJECT.CLIENT_ID = STAFF_PROJECT_ASSIGNMENT.CLIENT_ID AND
STAFF_PROJECT_ASSIGNMENT.ASSIGNMENT_ID = ASSIGNMENT.ASSIGNMENT_ID AND
STAFF.STAFF_ID = STAFF_PROJECT_ASSIGNMENT.STAFF_ID
ORDER BY PROJECT.NAME;


CREATE VIEW "v_Experience" AS
SELECT "CONTRACT"."CONTRACT_ID", "FIRSTNAME", "LASTNAME", "SERVICE"."NAME" AS "ROLE", "CLIENT"."NAME" AS "CUSTOMER", "CITY"."NAME" AS "CITY", "COUNTRY"."NAME" AS "COUNTRY"
FROM "SERVICE", "CLIENT", "CONTRACT", "STAFF", "PROJECT", "COUNTRY", "CITY", "LOCATION", "STAFF_PROJECT_ASSIGNMENT", "SUPPLIER", "CONTRACT_SERVICE_AGREEMENT", "EMPLOYMENT_CONTRACT", "SUPPLY_CONTRACT"
WHERE CITY.COUNTRY_ID = COUNTRY.COUNTRY_ID AND
LOCATION.CITY_ID = CITY.CITY_ID AND 
LOCATION.COUNTRY_ID = CITY.COUNTRY_ID AND 
LOCATION.PROJECT_ID = PROJECT.PROJECT_ID AND
PROJECT.CLIENT_ID = CLIENT.CLIENT_ID AND
CLIENT.CLIENT_ID = CONTRACT.CLIENT_ID AND
PROJECT.PROJECT_ID = STAFF_PROJECT_ASSIGNMENT.PROJECT_ID AND
PROJECT.CLIENT_ID = STAFF_PROJECT_ASSIGNMENT.CLIENT_ID AND
STAFF_PROJECT_ASSIGNMENT.STAFF_ID = STAFF.STAFF_ID AND
CONTRACT.CONTRACT_ID = CONTRACT_SERVICE_AGREEMENT.CONTRACT_ID AND
CONTRACT.CLIENT_ID  = CONTRACT_SERVICE_AGREEMENT.CLIENT_ID AND
CONTRACT_SERVICE_AGREEMENT.SERVICE_ID = SERVICE.SERVICE_ID  AND
CONTRACT.CONTRACT_ID = SUPPLY_CONTRACT.CONTRACT_ID AND
CONTRACT.CLIENT_ID = SUPPLY_CONTRACT.CLIENT_ID AND
SUPPLIER.SUPPLIER_ID = SUPPLY_CONTRACT.SUPPLIER_ID AND
SUPPLIER.SUPPLIER_ID = EMPLOYMENT_CONTRACT.SUPPLIER_ID AND
EMPLOYMENT_CONTRACT.STAFF_ID = STAFF.STAFF_ID
GROUP BY "CONTRACT"."CONTRACT_ID", "FIRSTNAME", "LASTNAME", "SERVICE"."NAME", "CLIENT"."NAME", "CITY"."NAME", "COUNTRY"."NAME";

CREATE VIEW "v_Resume" AS
SELECT "CONTRACT"."CONTRACT_ID", "CONTRACT"."NAME" AS "CONTRACT", "FIRSTNAME", "LASTNAME", "SERVICE"."NAME" AS "ROLE", "CLIENT"."NAME" AS "CUSTOMER", "SUPPLIER"."NAME" AS "SUPPLIER", "CITY"."NAME" AS "CITY", "COUNTRY"."NAME" AS "COUNTRY", "PROJECT"."NAME" AS "PROJECT", "ASSIGNMENT"."DESC" AS "RESPONSIBILITY", "START_DATE", "END_DATE"
FROM "CLIENT", "COUNTRY", "PROJECT", "CONTRACT", "STAFF_PROJECT_ASSIGNMENT", "SERVICE", "STAFF", "CITY", "SUPPLIER", "LOCATION", "ASSIGNMENT", "CONTRACT_SERVICE_AGREEMENT", "SUPPLY_CONTRACT"
WHERE CITY.COUNTRY_ID                         = COUNTRY.COUNTRY_ID AND
LOCATION.CITY_ID                        = CITY.CITY_ID AND 
LOCATION.COUNTRY_ID                     = CITY.COUNTRY_ID AND 
LOCATION.PROJECT_ID                     = PROJECT.PROJECT_ID AND
PROJECT.CLIENT_ID                       = CLIENT.CLIENT_ID AND
CLIENT.CLIENT_ID                        = CONTRACT.CLIENT_ID AND
PROJECT.PROJECT_ID                      = STAFF_PROJECT_ASSIGNMENT.PROJECT_ID AND
PROJECT.CLIENT_ID                       = STAFF_PROJECT_ASSIGNMENT.CLIENT_ID AND
STAFF_PROJECT_ASSIGNMENT.STAFF_ID       = STAFF.STAFF_ID AND
CONTRACT.CONTRACT_ID                    = CONTRACT_SERVICE_AGREEMENT.CONTRACT_ID AND
CONTRACT.CLIENT_ID                      = CONTRACT_SERVICE_AGREEMENT.CLIENT_ID AND
CONTRACT_SERVICE_AGREEMENT.SERVICE_ID   = SERVICE.SERVICE_ID  AND
CONTRACT.CONTRACT_ID                    = SUPPLY_CONTRACT.CONTRACT_ID AND
CONTRACT.CLIENT_ID                      = SUPPLY_CONTRACT.CLIENT_ID AND
SUPPLIER.SUPPLIER_ID                    = SUPPLY_CONTRACT.SUPPLIER_ID AND
STAFF.STAFF_ID                          = SUPPLY_CONTRACT.STAFF_ID AND
ASSIGNMENT.ASSIGNMENT_ID                = STAFF_PROJECT_ASSIGNMENT.ASSIGNMENT_ID
GROUP BY "CONTRACT"."CONTRACT_ID", "CONTRACT"."NAME", "FIRSTNAME", "LASTNAME", "SERVICE"."NAME", "CLIENT"."NAME", "CITY"."NAME", "COUNTRY"."NAME", "PROJECT"."NAME", "ASSIGNMENT"."DESC", "SUPPLIER"."NAME", "START_DATE", "END_DATE";
commit;