-- Drop relationships and keys section -------------------------------------------------
ALTER TABLE "AGREEMENT" DROP CONSTRAINT "ENGAGES";
ALTER TABLE "AGREEMENT" DROP CONSTRAINT "PROVIDES";
ALTER TABLE "ASSIGNMENT" DROP CONSTRAINT "EXECUTES";
ALTER TABLE "ASSIGNMENT" DROP CONSTRAINT "IS COMPOSED OF";
ALTER TABLE "ASSIGNMENT" DROP CONSTRAINT "WORKS ON";
ALTER TABLE "CITY" DROP CONSTRAINT "HAS A";
ALTER TABLE "CONTRACT" DROP CONSTRAINT "SIGNS";
ALTER TABLE "EMPLOYMENT_CONTRACT" DROP CONSTRAINT "EMPLOYS";
ALTER TABLE "EMPLOYMENT_CONTRACT" DROP CONSTRAINT "IS EMPLOYED";
ALTER TABLE "ENROLMENT" DROP CONSTRAINT "ENROLS";
ALTER TABLE "ENROLMENT" DROP CONSTRAINT "IN";
ALTER TABLE "INTEREST" DROP CONSTRAINT "HAS";
ALTER TABLE "LOCATION" DROP CONSTRAINT "ESTABLISHES A";
ALTER TABLE "LOCATION" DROP CONSTRAINT "IS BASED";
ALTER TABLE "PROJECT" DROP CONSTRAINT "CONTROLS";
ALTER TABLE "STAFF_SKILL" DROP CONSTRAINT "IS USED";
ALTER TABLE "STAFF_SKILL" DROP CONSTRAINT "USES";
ALTER TABLE "SUPPLY_CONTRACT" DROP CONSTRAINT "AGREES";
ALTER TABLE "SUPPLY_CONTRACT" DROP CONSTRAINT "COMMITS TO";
ALTER TABLE "SUPPLY_CONTRACT" DROP CONSTRAINT "WORKS IN";
ALTER TABLE "AGREEMENT" DROP CONSTRAINT "AGREEMENT_PK";
ALTER TABLE "ASSIGNMENT" DROP CONSTRAINT "ASSIGNMENT_PK";
ALTER TABLE "CITY" DROP CONSTRAINT "CITY_AK";
ALTER TABLE "CITY" DROP CONSTRAINT "CITY_PK";
ALTER TABLE "CLIENT" DROP CONSTRAINT "CLIENT_AK";
ALTER TABLE "CLIENT" DROP CONSTRAINT "CLIENT_PK";
ALTER TABLE "CONTRACT" DROP CONSTRAINT "CONTRACT_AK";
ALTER TABLE "CONTRACT" DROP CONSTRAINT "CONTRACT_PK";
ALTER TABLE "COUNTRY" DROP CONSTRAINT "COUNTRY_AK";
ALTER TABLE "COUNTRY" DROP CONSTRAINT "COUNTRY_PK";
ALTER TABLE "COURSE" DROP CONSTRAINT "COURSE_AK";
ALTER TABLE "COURSE" DROP CONSTRAINT "COURSE_PK";
ALTER TABLE "EMPLOYMENT_CONTRACT" DROP CONSTRAINT "EMPLOYMENT_CONTRACT_PK";
ALTER TABLE "ENROLMENT" DROP CONSTRAINT "ENROLMENT_PK";
ALTER TABLE "INTEREST" DROP CONSTRAINT "INTEREST_PK";
ALTER TABLE "LOCATION" DROP CONSTRAINT "LOCATION_PK";
ALTER TABLE "PROJECT" DROP CONSTRAINT "PROJECT_AK";
ALTER TABLE "PROJECT" DROP CONSTRAINT "PROJECT_PK";
ALTER TABLE "SERVICE" DROP CONSTRAINT "SERVICE_AK";
ALTER TABLE "SERVICE" DROP CONSTRAINT "SERVICE_PK";
ALTER TABLE "SKILL" DROP CONSTRAINT "SKILL_AK";
ALTER TABLE "SKILL" DROP CONSTRAINT "SKILL_PK";
ALTER TABLE "STAFF" DROP CONSTRAINT "STAFF_AK";
ALTER TABLE "STAFF" DROP CONSTRAINT "STAFF_PK";
ALTER TABLE "STAFF_SKILL" DROP CONSTRAINT "STAFF SKILL_PK";
ALTER TABLE "SUPPLIER" DROP CONSTRAINT "SUPPLIER_AK";
ALTER TABLE "SUPPLIER" DROP CONSTRAINT "SUPPLIER_PK";
ALTER TABLE "SUPPLY_CONTRACT" DROP CONSTRAINT "SUPPLY_CONTRACT_PK";
ALTER TABLE "TASK" DROP CONSTRAINT "TASK_PK";

-- Drop views section --------------------------------------------------- 

DROP VIEW "v_Experience";
DROP VIEW "v_ProjectTask";
DROP VIEW "v_Resume";

-- DROP TABLE IF EXISTSs section ---------------------------------------------------

DROP TABLE "AGREEMENT";
DROP TABLE "ASSIGNMENT";
DROP TABLE "CITY";
DROP TABLE "CLIENT";
DROP TABLE "CONTRACT";
DROP TABLE "COUNTRY";
DROP TABLE "COURSE";
DROP TABLE "EMPLOYMENT_CONTRACT";
DROP TABLE "ENROLMENT";
DROP TABLE "INTEREST";
DROP TABLE "LOCATION";
DROP TABLE "PROJECT";
DROP TABLE "SERVICE";
DROP TABLE "SKILL";
DROP TABLE "STAFF";
DROP TABLE "STAFF_SKILL";
DROP TABLE "SUPPLIER";
DROP TABLE "SUPPLY_CONTRACT";
DROP TABLE "TASK";

-- DROP SEQUENCE IF EXISTSs section --------------------------------------------------- 

DROP SEQUENCE "CITY_SEQ";
DROP SEQUENCE "CLIENT_SEQ";
DROP SEQUENCE "CONTRACT_SEQ";
DROP SEQUENCE "COUNTRY_SEQ";
DROP SEQUENCE "COURSE_SEQ";
DROP SEQUENCE "EMPLOYMENT_CONTRACT_SEQ";
DROP SEQUENCE "INTEREST_SEQ";
DROP SEQUENCE "PROJECT_SEQ";
DROP SEQUENCE "SERVICE_SEQ";
DROP SEQUENCE "SKILL_SEQ";
DROP SEQUENCE "STAFF_SEQ";
DROP SEQUENCE "SUPPLIER_SEQ";
DROP SEQUENCE "TASK_SEQ";

COMMIT;
