-- Drop relationships section -------------------------------------------------

ALTER TABLE "SUPPLY_CONTRACT" DROP CONSTRAINT "WORKS IN";
ALTER TABLE "SUPPLY_CONTRACT" DROP CONSTRAINT "COMMITS TO";
ALTER TABLE "SUPPLY_CONTRACT" DROP CONSTRAINT "AGREES";
ALTER TABLE "EMPLOYMENT_CONTRACT" DROP CONSTRAINT "EMPLOYS";
ALTER TABLE "EMPLOYMENT_CONTRACT" DROP CONSTRAINT "IS EMPLOYED";
ALTER TABLE "CONTRACT_SERVICE_AGREEMENT" DROP CONSTRAINT "PROVIDES";
ALTER TABLE "CONTRACT_SERVICE_AGREEMENT" DROP CONSTRAINT "ENGAGES";
ALTER TABLE "STAFF_PROJECT_ASSIGNMENT" DROP CONSTRAINT "ASSIGNS";
ALTER TABLE "STAFF_PROJECT_ASSIGNMENT" DROP CONSTRAINT "WORKS ON";
ALTER TABLE "STAFF_PROJECT_ASSIGNMENT" DROP CONSTRAINT "IS COMPOSED OF";
ALTER TABLE "LOCATION" DROP CONSTRAINT "ESTABLISHES A";
ALTER TABLE "LOCATION" DROP CONSTRAINT "IS BASED";
ALTER TABLE "PROJECT" DROP CONSTRAINT "CONTROLS";
ALTER TABLE "ENROLMENT" DROP CONSTRAINT "ENROLS";
ALTER TABLE "ENROLMENT" DROP CONSTRAINT "IN";
ALTER TABLE "STAFF_SKILL" DROP CONSTRAINT "IS USED";
ALTER TABLE "STAFF_SKILL" DROP CONSTRAINT "USES";
ALTER TABLE "INTEREST" DROP CONSTRAINT "HAS";
ALTER TABLE "CITY" DROP CONSTRAINT "HAS A";
ALTER TABLE "CONTRACT" DROP CONSTRAINT "SIGNS";


-- Drop views section --------------------------------------------------- 

DROP VIEW "v_Resume";
DROP VIEW "v_Experience";
DROP VIEW "v_ProjectTask";


-- DROP TABLE IF EXISTSs section ---------------------------------------------------

DROP TABLE "SUPPLY_CONTRACT";
DROP TABLE "EMPLOYMENT_CONTRACT";
DROP TABLE "CONTRACT_SERVICE_AGREEMENT";
DROP TABLE "ASSIGNMENT";
DROP TABLE "LOCATION";
DROP TABLE "SUPPLIER";
DROP TABLE "ENROLMENT";
DROP TABLE "COURSE";
DROP TABLE "STAFF_SKILL";
DROP TABLE "CITY";
DROP TABLE "INTEREST";
DROP TABLE "SERVICE";
DROP TABLE "STAFF";
DROP TABLE "SKILL";
DROP TABLE "STAFF_PROJECT_ASSIGNMENT";
DROP TABLE "COUNTRY";
DROP TABLE "CONTRACT";
DROP TABLE "CLIENT";
DROP TABLE "PROJECT";


-- DROP SEQUENCE IF EXISTSs section --------------------------------------------------- 

DROP SEQUENCE "EMPLOYMENT_CONTRACT_SEQ";
DROP SEQUENCE "COURSE_SEQ";
DROP SEQUENCE "CONTRACT_SEQ";
DROP SEQUENCE "SUPPLIER_SEQ";
DROP SEQUENCE "INTEREST_SEQ";
DROP SEQUENCE "SERVICE_SEQ";
DROP SEQUENCE "STAFF_SEQ";
DROP SEQUENCE "SKILL_SEQ";
DROP SEQUENCE "ASSIGNMENT_SEQ";
DROP SEQUENCE "COUNTRY_SEQ";
DROP SEQUENCE "CLIENT_SEQ";
DROP SEQUENCE "PROJECT_SEQ";
DROP SEQUENCE "CITY_SEQ";

COMMIT;
