--NOTE: to test script in ORACLE remove "IF NOT EXISTS" statements. 
-- Create sequences section -------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS "CITY_SEQ"
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 NOMINVALUE
 CACHE 20;
CREATE SEQUENCE IF NOT EXISTS  "PROJECT_SEQ"
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 NOMINVALUE
 CACHE 20;
CREATE SEQUENCE IF NOT EXISTS "CLIENT_SEQ"
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 NOMINVALUE
 CACHE 20;
CREATE SEQUENCE IF NOT EXISTS "COUNTRY_SEQ"
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 NOMINVALUE
 CACHE 20;
CREATE SEQUENCE IF NOT EXISTS "TASK_SEQ"
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 NOMINVALUE
 CACHE 20;
CREATE SEQUENCE IF NOT EXISTS "SKILL_SEQ"
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 NOMINVALUE
 CACHE 20;
CREATE SEQUENCE IF NOT EXISTS "STAFF_SEQ"
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 NOMINVALUE
 CACHE 20;
CREATE SEQUENCE IF NOT EXISTS "SERVICE_SEQ"
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 NOMINVALUE
 CACHE 20;
CREATE SEQUENCE IF NOT EXISTS "INTEREST_SEQ"
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 NOMINVALUE
 CACHE 20;
CREATE SEQUENCE IF NOT EXISTS "SUPPLIER_SEQ"
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 NOMINVALUE
 CACHE 20;
CREATE SEQUENCE IF NOT EXISTS "CONTRACT_SEQ"
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 NOMINVALUE
 CACHE 20; 
 CREATE SEQUENCE IF NOT EXISTS "COURSE_SEQ"
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 NOMINVALUE
 CACHE 20; 
 CREATE SEQUENCE IF NOT EXISTS "EMPLOYMENT_CONTRACT_SEQ"
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 NOMINVALUE
 CACHE 20;
-- Create tables section -------------------------------------------------
-- Table PROJECT
CREATE TABLE  IF NOT EXISTS "PROJECT"(
  "PROJECT_ID" Integer NOT NULL,
  "NAME" Varchar2(30 ) NOT NULL,
  "VERSION" Varchar2(30 ) NOT NULL,
  "CLIENT_ID" Integer NOT NULL,
  "DESC" Varchar2(400 )
);
-- Table CLIENT
CREATE TABLE  IF NOT EXISTS "CLIENT"(
  "CLIENT_ID" Integer NOT NULL,
  "NAME" Varchar2(50 ) NOT NULL,
  "WEBSITE" Varchar2(100 )
);
-- Table CONTRACT
CREATE TABLE  IF NOT EXISTS "CONTRACT"(
  "CONTRACT_ID" Integer NOT NULL,
  "CLIENT_ID" Integer NOT NULL,
  "NAME" Varchar2(30 ) NOT NULL
);
-- Table COUNTRY
CREATE TABLE  IF NOT EXISTS "COUNTRY"(
  "COUNTRY_ID" Integer NOT NULL,
  "NAME" Varchar2(30 ) NOT NULL
);
-- Table ASSIGNMENT
CREATE TABLE  IF NOT EXISTS "ASSIGNMENT"(
  "TASK_ID" Integer NOT NULL,
  "PROJECT_ID" Integer NOT NULL,
  "CLIENT_ID" Integer NOT NULL,
  "STAFF_ID" Integer NOT NULL
);
-- Table SKILL
CREATE TABLE  IF NOT EXISTS "SKILL"(
  "SKILL_ID" Integer NOT NULL,
  "NAME" Varchar2(30 ) NOT NULL
);
-- Table STAFF
CREATE TABLE  IF NOT EXISTS "STAFF"(
  "STAFF_ID" Integer NOT NULL,
  "FIRSTNAME" Varchar2(30 ) NOT NULL,
  "LASTNAME" Varchar2(30 ) NOT NULL,
  "BIRTH_DATE" Date NOT NULL
);
-- Table SERVICE
CREATE TABLE  IF NOT EXISTS "SERVICE"(
  "SERVICE_ID" Integer NOT NULL,
  "NAME" Varchar2(50 ) NOT NULL,
  "DESC" Varchar2(400 )
);
-- Table INTEREST
CREATE TABLE  IF NOT EXISTS "INTEREST"(
  "INTEREST_ID" Integer NOT NULL,
  "STAFF_ID" Integer,
  "DESC" Varchar2(500 )
);
-- Table CITY
CREATE TABLE  IF NOT EXISTS "CITY"(
  "CITY_ID" Integer NOT NULL,
  "COUNTRY_ID" Integer NOT NULL,
  "NAME" Varchar2(30 ) NOT NULL
);
-- Table STAFF_SKILL
CREATE TABLE  IF NOT EXISTS "STAFF_SKILL"(
  "STAFF_ID" Integer NOT NULL,
  "SKILL_ID" Integer NOT NULL,
  "YEARS_OF_EXPERIENCE" Integer,
  "ENDORSEMENT" Integer
);
-- Table COURSE
CREATE TABLE  IF NOT EXISTS "COURSE"(
  "COURSE_ID" Integer NOT NULL,
  "TITLE" Varchar2(100 ) NOT NULL,
  "CREDITS" Integer
);
-- Table ENROLMENT
CREATE TABLE  IF NOT EXISTS "ENROLMENT"(
  "COURSE_ID" Integer NOT NULL,
  "STAFF_ID" Integer NOT NULL,
  "GRADE" Varchar2(30 ),
  "START_DATE" Date,
  "END_DATE" Date,
  "DURATION" Integer
);
-- Table SUPPLIER
CREATE TABLE  IF NOT EXISTS "SUPPLIER"(
  "SUPPLIER_ID" Integer NOT NULL,
  "NAME" Varchar2(30 ) NOT NULL
);
-- Table LOCATION
CREATE TABLE  IF NOT EXISTS "LOCATION"(
  "PROJECT_ID" Integer NOT NULL,
  "CLIENT_ID" Integer NOT NULL,
  "CITY_ID" Integer NOT NULL,
  "COUNTRY_ID" Integer NOT NULL
);
-- Table TASK
CREATE TABLE  IF NOT EXISTS "TASK"(
  "TASK_ID" Integer NOT NULL,
  "DESC" Varchar2(255 ) NOT NULL,
  "PRIORITY" Integer
);
-- Table AGREEMENT
CREATE TABLE  IF NOT EXISTS "AGREEMENT"(
  "CLIENT_ID" Integer NOT NULL,
  "CONTRACT_ID" Integer NOT NULL,
  "SERVICE_ID" Integer NOT NULL
);
-- Table EMPLOYMENT_CONTRACT
CREATE TABLE  IF NOT EXISTS "EMPLOYMENT_CONTRACT"(
  "EMPLOYMENT_CONTRACT_ID" Integer NOT NULL,
  "STAFF_ID" Integer NOT NULL,
  "SUPPLIER_ID" Integer NOT NULL,
  "START_DATE" Date NOT NULL,
  "END_DATE" Date
);
-- Table SUPPLY_CONTRACT
CREATE TABLE  IF NOT EXISTS "SUPPLY_CONTRACT"(
  "SUPPLIER_ID" Integer NOT NULL,
  "CLIENT_ID" Integer NOT NULL,
  "CONTRACT_ID" Integer NOT NULL,
  "STAFF_ID" Integer NOT NULL,
  "START_DATE" Date NOT NULL,
  "END_DATE" Date
)
;
-- Add keys for table SUPPLY_CONTRACT
ALTER TABLE "SUPPLY_CONTRACT" ADD CONSTRAINT IF NOT EXISTS "SUPPLY_CONTRACT_PK" PRIMARY KEY ("SUPPLIER_ID","CLIENT_ID","CONTRACT_ID","STAFF_ID");
-- Add keys for table PROJECT
ALTER TABLE "PROJECT" ADD CONSTRAINT IF NOT EXISTS "PROJECT_PK" PRIMARY KEY ("CLIENT_ID","PROJECT_ID");
ALTER TABLE "PROJECT" ADD CONSTRAINT IF NOT EXISTS "PROJECT_AK" UNIQUE ("NAME","VERSION");
-- Add keys for table CLIENT
ALTER TABLE "CLIENT" ADD CONSTRAINT IF NOT EXISTS "CLIENT_PK" PRIMARY KEY ("CLIENT_ID");
ALTER TABLE "CLIENT" ADD CONSTRAINT IF NOT EXISTS "CLIENT_AK" UNIQUE ("NAME");
-- Add keys for table CONTRACT
ALTER TABLE "CONTRACT" ADD CONSTRAINT IF NOT EXISTS "CONTRACT_PK" PRIMARY KEY ("CLIENT_ID","CONTRACT_ID");
ALTER TABLE "CONTRACT" ADD CONSTRAINT IF NOT EXISTS "CONTRACT_AK" UNIQUE ("NAME");
-- Add keys for table COUNTRY
ALTER TABLE "COUNTRY" ADD CONSTRAINT IF NOT EXISTS "COUNTRY_PK" PRIMARY KEY ("COUNTRY_ID");
ALTER TABLE "COUNTRY" ADD CONSTRAINT IF NOT EXISTS "COUNTRY_AK" UNIQUE ("NAME");
-- Add keys for table ASSIGNMENT
ALTER TABLE "ASSIGNMENT" ADD CONSTRAINT IF NOT EXISTS "ASSIGNMENT_PK" PRIMARY KEY ("TASK_ID","PROJECT_ID","STAFF_ID","CLIENT_ID");
-- Add keys for table SKILL
ALTER TABLE "SKILL" ADD CONSTRAINT IF NOT EXISTS "SKILL_PK" PRIMARY KEY ("SKILL_ID");
ALTER TABLE "SKILL" ADD CONSTRAINT IF NOT EXISTS "SKILL_AK" UNIQUE ("NAME");
-- Add keys for table STAFF
ALTER TABLE "STAFF" ADD CONSTRAINT IF NOT EXISTS "STAFF_PK" PRIMARY KEY ("STAFF_ID");
ALTER TABLE "STAFF" ADD CONSTRAINT IF NOT EXISTS "STAFF_AK" UNIQUE ("FIRSTNAME","LASTNAME","BIRTH_DATE");
-- Add keys for table SERVICE
ALTER TABLE "SERVICE" ADD CONSTRAINT IF NOT EXISTS "SERVICE_PK" PRIMARY KEY ("SERVICE_ID");
ALTER TABLE "SERVICE" ADD CONSTRAINT IF NOT EXISTS "SERVICE_AK" UNIQUE ("NAME");
-- Add keys for table INTEREST
ALTER TABLE "INTEREST" ADD CONSTRAINT IF NOT EXISTS "INTEREST_PK" PRIMARY KEY ("INTEREST_ID");
-- Add keys for table CITY
ALTER TABLE "CITY" ADD CONSTRAINT IF NOT EXISTS "CITY_PK" PRIMARY KEY ("CITY_ID","COUNTRY_ID");
ALTER TABLE "CITY" ADD CONSTRAINT IF NOT EXISTS "CITY_AK" UNIQUE ("NAME");
-- Add keys for table STAFF_SKILL
ALTER TABLE "STAFF_SKILL" ADD CONSTRAINT IF NOT EXISTS "STAFF_SKILL_PK" PRIMARY KEY ("STAFF_ID","SKILL_ID");
-- Add keys for table COURSE
ALTER TABLE "COURSE" ADD CONSTRAINT IF NOT EXISTS "COURSE_PK" PRIMARY KEY ("COURSE_ID");
ALTER TABLE "COURSE" ADD CONSTRAINT IF NOT EXISTS "COURSE_AK" UNIQUE ("TITLE");
-- Add keys for table ENROLMENT
ALTER TABLE "ENROLMENT" ADD CONSTRAINT IF NOT EXISTS "ENROLMENT_PK" PRIMARY KEY ("COURSE_ID","STAFF_ID");
-- Add keys for table SUPPLIER
ALTER TABLE "SUPPLIER" ADD CONSTRAINT IF NOT EXISTS "SUPPLIER_PK" PRIMARY KEY ("SUPPLIER_ID");
ALTER TABLE "SUPPLIER" ADD CONSTRAINT IF NOT EXISTS "SUPPLIER_AK" UNIQUE ("NAME");
-- Add keys for table LOCATION
ALTER TABLE "LOCATION" ADD CONSTRAINT IF NOT EXISTS "LOCATION_PK" PRIMARY KEY ("CLIENT_ID","CITY_ID","COUNTRY_ID","PROJECT_ID");
-- Add keys for table TASK
ALTER TABLE "TASK" ADD CONSTRAINT IF NOT EXISTS "TASK_PK" PRIMARY KEY ("TASK_ID");
ALTER TABLE "TASK" ADD CONSTRAINT IF NOT EXISTS "TASK_AK" UNIQUE ("DESC");
-- Add keys for table AGREEMENT
ALTER TABLE "AGREEMENT" ADD CONSTRAINT IF NOT EXISTS "AGREEMENT_PK" PRIMARY KEY ("CLIENT_ID","CONTRACT_ID","SERVICE_ID");
-- Add keys for table EMPLOYMENT_CONTRACT
ALTER TABLE "EMPLOYMENT_CONTRACT" ADD CONSTRAINT IF NOT EXISTS "EMPLOYMENT_CONTRACT_PK" PRIMARY KEY ("EMPLOYMENT_CONTRACT_ID","STAFF_ID","SUPPLIER_ID");
-- Create foreign keys (relationships) section ------------------------------------------------- 
ALTER TABLE "CONTRACT" ADD CONSTRAINT IF NOT EXISTS "SIGNS" FOREIGN KEY ("CLIENT_ID") REFERENCES "CLIENT" ("CLIENT_ID");
ALTER TABLE "CITY" ADD CONSTRAINT IF NOT EXISTS "HAS A" FOREIGN KEY ("COUNTRY_ID") REFERENCES "COUNTRY" ("COUNTRY_ID");
ALTER TABLE "INTEREST" ADD CONSTRAINT IF NOT EXISTS "HAS" FOREIGN KEY ("STAFF_ID") REFERENCES "STAFF" ("STAFF_ID") ON DELETE CASCADE;
ALTER TABLE "STAFF_SKILL" ADD CONSTRAINT IF NOT EXISTS "USES" FOREIGN KEY ("STAFF_ID") REFERENCES "STAFF" ("STAFF_ID") ON DELETE CASCADE;
ALTER TABLE "STAFF_SKILL" ADD CONSTRAINT IF NOT EXISTS "IS USED" FOREIGN KEY ("SKILL_ID") REFERENCES "SKILL" ("SKILL_ID") ON DELETE CASCADE;
ALTER TABLE "ENROLMENT" ADD CONSTRAINT IF NOT EXISTS "IN" FOREIGN KEY ("COURSE_ID") REFERENCES "COURSE" ("COURSE_ID") ON DELETE CASCADE;
ALTER TABLE "ENROLMENT" ADD CONSTRAINT IF NOT EXISTS "ENROLS" FOREIGN KEY ("STAFF_ID") REFERENCES "STAFF" ("STAFF_ID") ON DELETE CASCADE;
ALTER TABLE "PROJECT" ADD CONSTRAINT IF NOT EXISTS "CONTROLS" FOREIGN KEY ("CLIENT_ID") REFERENCES "CLIENT" ("CLIENT_ID");
ALTER TABLE "LOCATION" ADD CONSTRAINT IF NOT EXISTS "IS BASED" FOREIGN KEY ("CLIENT_ID", "PROJECT_ID") REFERENCES "PROJECT" ("CLIENT_ID", "PROJECT_ID") ON DELETE CASCADE;
ALTER TABLE "LOCATION" ADD CONSTRAINT IF NOT EXISTS "ESTABLISHES A" FOREIGN KEY ("CITY_ID", "COUNTRY_ID") REFERENCES "CITY" ("CITY_ID", "COUNTRY_ID") ON DELETE CASCADE;
ALTER TABLE "ASSIGNMENT" ADD CONSTRAINT IF NOT EXISTS "IS COMPOSED OF" FOREIGN KEY ("CLIENT_ID", "PROJECT_ID") REFERENCES "PROJECT" ("CLIENT_ID", "PROJECT_ID");
ALTER TABLE "ASSIGNMENT" ADD CONSTRAINT IF NOT EXISTS "WORKS ON" FOREIGN KEY ("STAFF_ID") REFERENCES "STAFF" ("STAFF_ID");
ALTER TABLE "ASSIGNMENT" ADD CONSTRAINT IF NOT EXISTS "EXECUTES" FOREIGN KEY ("TASK_ID") REFERENCES "TASK" ("TASK_ID");
ALTER TABLE "AGREEMENT" ADD CONSTRAINT IF NOT EXISTS "ENGAGES" FOREIGN KEY ("CLIENT_ID", "CONTRACT_ID") REFERENCES "CONTRACT" ("CLIENT_ID", "CONTRACT_ID") ON DELETE CASCADE;
ALTER TABLE "AGREEMENT" ADD CONSTRAINT IF NOT EXISTS "PROVIDES" FOREIGN KEY ("SERVICE_ID") REFERENCES "SERVICE" ("SERVICE_ID") ON DELETE CASCADE;
ALTER TABLE "EMPLOYMENT_CONTRACT" ADD CONSTRAINT IF NOT EXISTS "IS EMPLOYED" FOREIGN KEY ("STAFF_ID") REFERENCES "STAFF" ("STAFF_ID") ON DELETE CASCADE;
ALTER TABLE "EMPLOYMENT_CONTRACT" ADD CONSTRAINT IF NOT EXISTS "EMPLOYS" FOREIGN KEY ("SUPPLIER_ID") REFERENCES "SUPPLIER" ("SUPPLIER_ID") ON DELETE CASCADE;
ALTER TABLE "SUPPLY_CONTRACT" ADD CONSTRAINT IF NOT EXISTS "AGREES" FOREIGN KEY ("SUPPLIER_ID") REFERENCES "SUPPLIER" ("SUPPLIER_ID") ON DELETE CASCADE;
ALTER TABLE "SUPPLY_CONTRACT" ADD CONSTRAINT IF NOT EXISTS "COMMITS TO" FOREIGN KEY ("CLIENT_ID", "CONTRACT_ID") REFERENCES "CONTRACT" ("CLIENT_ID", "CONTRACT_ID") ON DELETE CASCADE;
ALTER TABLE "SUPPLY_CONTRACT" ADD CONSTRAINT IF NOT EXISTS "WORKS IN" FOREIGN KEY ("STAFF_ID") REFERENCES "STAFF" ("STAFF_ID") ON DELETE CASCADE;
commit;