--NOTE: to test script in ORACLE remove "IF EXISTS" statements, add drop contraints statements. 
-- Drop views section --------------------------------------------------- 

DROP VIEW IF EXISTS "v_Resume";
DROP VIEW IF EXISTS "v_Experience";
DROP VIEW IF EXISTS "v_ProjectTask";


-- DROP TABLE IF EXISTSs section ---------------------------------------------------

DROP TABLE IF EXISTS "SUPPLY_CONTRACT";
DROP TABLE IF EXISTS "EMPLOYMENT_CONTRACT";
DROP TABLE IF EXISTS "AGREEMENT";
DROP TABLE IF EXISTS "ASSIGNMENT";
DROP TABLE IF EXISTS "LOCATION";
DROP TABLE IF EXISTS "SUPPLIER";
DROP TABLE IF EXISTS "ENROLMENT";
DROP TABLE IF EXISTS "COURSE";
DROP TABLE IF EXISTS "STAFF_SKILL";
DROP TABLE IF EXISTS "CITY";
DROP TABLE IF EXISTS "INTEREST";
DROP TABLE IF EXISTS "SERVICE";
DROP TABLE IF EXISTS "STAFF";
DROP TABLE IF EXISTS "SKILL";
DROP TABLE IF EXISTS "TASK";
DROP TABLE IF EXISTS "COUNTRY";
DROP TABLE IF EXISTS "CONTRACT";
DROP TABLE IF EXISTS "CLIENT";
DROP TABLE IF EXISTS "PROJECT";


-- DROP SEQUENCE IF EXISTSs section --------------------------------------------------- 

DROP SEQUENCE IF EXISTS "EMPLOYMENT_CONTRACT_SEQ";
DROP SEQUENCE IF EXISTS "COURSE_SEQ";
DROP SEQUENCE IF EXISTS "CONTRACT_SEQ";
DROP SEQUENCE IF EXISTS "SUPPLIER_SEQ";
DROP SEQUENCE IF EXISTS "INTEREST_SEQ";
DROP SEQUENCE IF EXISTS "SERVICE_SEQ";
DROP SEQUENCE IF EXISTS "STAFF_SEQ";
DROP SEQUENCE IF EXISTS "SKILL_SEQ";
DROP SEQUENCE IF EXISTS "TASK_SEQ";
DROP SEQUENCE IF EXISTS "COUNTRY_SEQ";
DROP SEQUENCE IF EXISTS "CLIENT_SEQ";
DROP SEQUENCE IF EXISTS "PROJECT_SEQ";
DROP SEQUENCE IF EXISTS "CITY_SEQ";
commit;