package com.tecxis.resume.domain.util.function;

public enum ValidationResult {	
	SUCCESS,
	PROJECT_NAME_IS_NOT_VALID,
	PROJECT_VERSION_IS_NOT_VALID,
	PROJECT_CLIENT_IS_NOT_VALID,
	STAFF_FIRSTNAME_IS_NOT_VALID,
	STAFF_LASTNAME_IS_NOT_VALID,
	TASK_DESC_IS_NOT_VALID,
	CONTRACT_NAME_IS_NOT_VALID,
	CITY_IS_NOT_VALID,
	CITY_LOCATIONS_ARE_NOT_VALID,
	SERVICE_NAME_IS_NOT_VALID,
	COUNTRY_CITIES_ARE_NOT_VALID,
	COUNTRY_NAME_IS_NOT_VALID,
	CLIENT_NAME_IS_NOT_VALID
}
