package com.tecxis.resume.domain.util.function;

public enum ValidationResult {	
	SUCCESS,
	PROJECT_IS_NOT_VALID,
	STAFF_IS_NOT_VALID,
	TASK_IS_NOT_VALID,
	CONTRACT_IS_NOT_VALID,
	CITY_IS_NOT_VALID,
	SERVICE_IS_NOT_VALID,
	COUNTRY_CITIES_ARE_NOT_VALID,
	COUNTRY_NAME_IS_NOT_VALID
}
