--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "CITY" DROP CONSTRAINT "HAS A";

ALTER TABLE "CONTRACT" DROP CONSTRAINT "SIGNS";

ALTER TABLE "CONTRACT_SERVICE_AGREEMENT" DROP CONSTRAINT "ENGAGES";

ALTER TABLE "CONTRACT_SERVICE_AGREEMENT" DROP CONSTRAINT "PROVIDES";

ALTER TABLE "EMPLOYMENT_CONTRACT" DROP CONSTRAINT "EMPLOYS";

ALTER TABLE "EMPLOYMENT_CONTRACT" DROP CONSTRAINT "IS EMPLOYED";

ALTER TABLE "ENROLMENT" DROP CONSTRAINT "ENROLS";

ALTER TABLE "ENROLMENT" DROP CONSTRAINT "IN";

ALTER TABLE "INTEREST" DROP CONSTRAINT "HAS";

ALTER TABLE "LOCATION" DROP CONSTRAINT "ESTABLISHES A";

ALTER TABLE "LOCATION" DROP CONSTRAINT "IS BASED";

ALTER TABLE "PROJECT" DROP CONSTRAINT "CONTROLS";

ALTER TABLE "STAFF_PROJECT_ASSIGNMENT" DROP CONSTRAINT "ASSIGNS";

ALTER TABLE "STAFF_PROJECT_ASSIGNMENT" DROP CONSTRAINT "IS COMPOSED OF";

ALTER TABLE "STAFF_PROJECT_ASSIGNMENT" DROP CONSTRAINT "WORKS ON";

ALTER TABLE "STAFF_SKILL" DROP CONSTRAINT "IS USED";

ALTER TABLE "STAFF_SKILL" DROP CONSTRAINT "USES";

ALTER TABLE "SUPPLY_CONTRACT" DROP CONSTRAINT "AGREES";

ALTER TABLE "SUPPLY_CONTRACT" DROP CONSTRAINT "COMMITS TO";

ALTER TABLE "SUPPLY_CONTRACT" DROP CONSTRAINT "WORKS IN";

ALTER TABLE "ASSIGNMENT" DROP CONSTRAINT "AK_ASSIGNMENT";

ALTER TABLE "ASSIGNMENT" DROP CONSTRAINT "PK_ASSIGNMENT";

ALTER TABLE "CITY" DROP CONSTRAINT "AK_CITY_NAME";

ALTER TABLE "CITY" DROP CONSTRAINT "PK_CITY";

ALTER TABLE "CLIENT" DROP CONSTRAINT "AK_CLIENT";

ALTER TABLE "CLIENT" DROP CONSTRAINT "PK_CUSTOMER_ID";

ALTER TABLE "CONTRACT" DROP CONSTRAINT "AK_CONTRACT_NAME";

ALTER TABLE "CONTRACT" DROP CONSTRAINT "PK_CONTRACT";

ALTER TABLE "CONTRACT_SERVICE_AGREEMENT" DROP CONSTRAINT "Key1";

ALTER TABLE "COUNTRY" DROP CONSTRAINT "AK_COUNTRY_NAME";

ALTER TABLE "COUNTRY" DROP CONSTRAINT "PK_COUNTRY_ID";

ALTER TABLE "COURSE" DROP CONSTRAINT "AK_COURSE";

ALTER TABLE "COURSE" DROP CONSTRAINT "PK_COURSE_ID";

ALTER TABLE "EMPLOYMENT_CONTRACT" DROP CONSTRAINT "PK_EMPLOYMENT_CONTRACT";

ALTER TABLE "ENROLMENT" DROP CONSTRAINT "PK_ENROLLMENT";

ALTER TABLE "INTEREST" DROP CONSTRAINT "PK_INTEREST_ID";

ALTER TABLE "LOCATION" DROP CONSTRAINT "PK_LOCATION";

ALTER TABLE "PROJECT" DROP CONSTRAINT "AK_PROJECT";

ALTER TABLE "PROJECT" DROP CONSTRAINT "PK_PROJECT";

ALTER TABLE "SERVICE" DROP CONSTRAINT "AK_SERVICE";

ALTER TABLE "SERVICE" DROP CONSTRAINT "PK_SERVICE_ID";

ALTER TABLE "SKILL" DROP CONSTRAINT "AK_SKILL_NAME";

ALTER TABLE "SKILL" DROP CONSTRAINT "PK_SKILL_ID";

ALTER TABLE "STAFF" DROP CONSTRAINT "AK_STAFF_NAME";

ALTER TABLE "STAFF" DROP CONSTRAINT "PK_STAFF_ID";

ALTER TABLE "STAFF_PROJECT_ASSIGNMENT" DROP CONSTRAINT "PK_ASSIGNMENT_ID";

ALTER TABLE "STAFF_SKILL" DROP CONSTRAINT "PK_SKILL_USED";

ALTER TABLE "SUPPLIER" DROP CONSTRAINT "AK_SUPPLIER_NAME";

ALTER TABLE "SUPPLIER" DROP CONSTRAINT "SUPPLIER_PK";

ALTER TABLE "SUPPLY_CONTRACT" DROP CONSTRAINT "SUPPLY_CONTRACT_PK";

DROP VIEW "v_Experience";

DROP VIEW "v_ProjectTask";

DROP VIEW "v_Resume";

DROP TABLE "ASSIGNMENT";

DROP TABLE "CITY";

DROP TABLE "CLIENT";

DROP TABLE "CONTRACT";

DROP TABLE "CONTRACT_SERVICE_AGREEMENT";

DROP TABLE "COUNTRY";

DROP TABLE "COURSE";

DROP TABLE "EMPLOYMENT_CONTRACT";

DROP TABLE "ENROLMENT";

DROP TABLE "INTEREST";

DROP TABLE "LOCATION";

DROP TABLE "PROJECT";

DROP TABLE "SERVICE";

DROP TABLE "SKILL";

DROP TABLE "STAFF";

DROP TABLE "STAFF_PROJECT_ASSIGNMENT";

DROP TABLE "STAFF_SKILL";

DROP TABLE "SUPPLIER";

DROP TABLE "SUPPLY_CONTRACT";

DROP SEQUENCE "ASSIGNMENT_SEQ";

DROP SEQUENCE "CITY_SEQ";

DROP SEQUENCE "CLIENT_SEQ";

DROP SEQUENCE "CONTRACT_SEQ";

DROP SEQUENCE "COUNTRY_SEQ";

DROP SEQUENCE "COURSE_SEQ";

DROP SEQUENCE "EMPLOYMENT_CONTRACT_SEQ";

DROP SEQUENCE "INTEREST_SEQ";

DROP SEQUENCE "PROJECT_SEQ";

DROP SEQUENCE "SERVICE_SEQ";

DROP SEQUENCE "SKILL_SEQ";

DROP SEQUENCE "STAFF_SEQ";

DROP SEQUENCE "SUPPLIER_SEQ";

CREATE SEQUENCE "ASSIGNMENT_SEQ"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	START WITH 1;

CREATE SEQUENCE "CITY_SEQ"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	START WITH 1;

CREATE SEQUENCE "CLIENT_SEQ"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	START WITH 1;

CREATE SEQUENCE "CONTRACT_SEQ"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	START WITH 1;

CREATE SEQUENCE "COUNTRY_SEQ"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	START WITH 1;

CREATE SEQUENCE "COURSE_SEQ"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	START WITH 1;

CREATE SEQUENCE "EMPLOYMENT_CONTRACT_SEQ"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	START WITH 1;

CREATE SEQUENCE "INTEREST_SEQ"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	START WITH 1;

CREATE SEQUENCE "PROJECT_SEQ"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	START WITH 1;

CREATE SEQUENCE "SERVICE_SEQ"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	START WITH 1;

CREATE SEQUENCE "SKILL_SEQ"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	START WITH 1;

CREATE SEQUENCE "STAFF_SEQ"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	START WITH 1;

CREATE SEQUENCE "SUPPLIER_SEQ"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999999999999999999999999
	START WITH 1;

CREATE TABLE "ASSIGNMENT" (
		"ASSIGNMENT_ID" NUMBER(38 , 0) NOT NULL,
		"DESC" VARCHAR2(255) NOT NULL,
		"PRIORITY" NUMBER(38 , 0)
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "CITY" (
		"CITY_ID" NUMBER(38 , 0) NOT NULL,
		"COUNTRY_ID" NUMBER(38 , 0) NOT NULL,
		"NAME" VARCHAR2(30) NOT NULL
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "CLIENT" (
		"CLIENT_ID" NUMBER(38 , 0) NOT NULL,
		"NAME" VARCHAR2(50) NOT NULL,
		"WEBSITE" VARCHAR2(100)
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "CONTRACT" (
		"CONTRACT_ID" NUMBER(38 , 0) NOT NULL,
		"CLIENT_ID" NUMBER(38 , 0) NOT NULL,
		"NAME" VARCHAR2(30) NOT NULL
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "CONTRACT_SERVICE_AGREEMENT" (
		"CLIENT_ID" NUMBER(38 , 0) NOT NULL,
		"CONTRACT_ID" NUMBER(38 , 0) NOT NULL,
		"SERVICE_ID" NUMBER(38 , 0) NOT NULL
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "COUNTRY" (
		"COUNTRY_ID" NUMBER(38 , 0) NOT NULL,
		"NAME" VARCHAR2(30) NOT NULL
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "COURSE" (
		"COURSE_ID" NUMBER(38 , 0) NOT NULL,
		"TITLE" VARCHAR2(100) NOT NULL,
		"CREDITS" NUMBER(38 , 0)
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "EMPLOYMENT_CONTRACT" (
		"EMPLOYMENT_CONTRACT_ID" NUMBER(38 , 0) NOT NULL,
		"STAFF_ID" NUMBER(38 , 0) NOT NULL,
		"SUPPLIER_ID" NUMBER(38 , 0) NOT NULL,
		"START_DATE" DATE NOT NULL,
		"END_DATE" DATE
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "ENROLMENT" (
		"COURSE_ID" NUMBER(38 , 0) NOT NULL,
		"STAFF_ID" NUMBER(38 , 0) NOT NULL,
		"GRADE" VARCHAR2(30),
		"START_DATE" DATE,
		"END_DATE" DATE,
		"DURATION" NUMBER(38 , 0)
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "INTEREST" (
		"INTEREST_ID" NUMBER(38 , 0) NOT NULL,
		"STAFF_ID" NUMBER(38 , 0),
		"DESC" VARCHAR2(500)
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "LOCATION" (
		"PROJECT_ID" NUMBER(38 , 0) NOT NULL,
		"CLIENT_ID" NUMBER(38 , 0) NOT NULL,
		"CITY_ID" NUMBER(38 , 0) NOT NULL,
		"COUNTRY_ID" NUMBER(38 , 0) NOT NULL
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "PROJECT" (
		"PROJECT_ID" NUMBER(38 , 0) NOT NULL,
		"NAME" VARCHAR2(30) NOT NULL,
		"VERSION" VARCHAR2(30) NOT NULL,
		"CLIENT_ID" NUMBER(38 , 0) NOT NULL,
		"DESC" VARCHAR2(400)
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "SERVICE" (
		"SERVICE_ID" NUMBER(38 , 0) NOT NULL,
		"NAME" VARCHAR2(50) NOT NULL,
		"DESC" VARCHAR2(400)
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "SKILL" (
		"SKILL_ID" NUMBER(38 , 0) NOT NULL,
		"NAME" VARCHAR2(30) NOT NULL
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "STAFF" (
		"STAFF_ID" NUMBER(38 , 0) NOT NULL,
		"FIRSTNAME" VARCHAR2(30) NOT NULL,
		"LASTNAME" VARCHAR2(30) NOT NULL,
		"BIRTH_DATE" DATE NOT NULL
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "STAFF_PROJECT_ASSIGNMENT" (
		"ASSIGNMENT_ID" NUMBER(38 , 0) NOT NULL,
		"PROJECT_ID" NUMBER(38 , 0) NOT NULL,
		"CLIENT_ID" NUMBER(38 , 0) NOT NULL,
		"STAFF_ID" NUMBER(38 , 0) NOT NULL
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "STAFF_SKILL" (
		"STAFF_ID" NUMBER(38 , 0) NOT NULL,
		"SKILL_ID" NUMBER(38 , 0) NOT NULL,
		"YEARS_OF_EXPERIENCE" NUMBER(38 , 0),
		"ENDORSEMENT" NUMBER(38 , 0)
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "SUPPLIER" (
		"SUPPLIER_ID" NUMBER(38 , 0) NOT NULL,
		"NAME" VARCHAR2(30) NOT NULL
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "SUPPLY_CONTRACT" (
		"SUPPLIER_ID" NUMBER(38 , 0) NOT NULL,
		"CLIENT_ID" NUMBER(38 , 0) NOT NULL,
		"CONTRACT_ID" NUMBER(38 , 0) NOT NULL,
		"STAFF_ID" NUMBER(38 , 0) NOT NULL,
		"START_DATE" DATE NOT NULL,
		"END_DATE" DATE
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE INDEX "AK_ASSIGNMENT_IDX"
	ON "ASSIGNMENT" ("DESC");

CREATE INDEX "AK_CITY_NAME_IDX"
	ON "CITY" ("NAME");

CREATE INDEX "AK_CLIENT_IDX"
	ON "CLIENT" ("NAME");

CREATE INDEX "AK_CONTRACT_NAME_IDX"
	ON "CONTRACT" ("NAME");

CREATE INDEX "AK_COUNTRY_NAME_IDX"
	ON "COUNTRY" ("NAME");

CREATE INDEX "AK_COURSE_IDX"
	ON "COURSE" ("TITLE");

CREATE INDEX "AK_PROJECT_IDX"
	ON "PROJECT" ("NAME","VERSION");

CREATE INDEX "AK_SERVICE_IDX"
	ON "SERVICE" ("NAME");

CREATE INDEX "AK_SKILL_NAME_IDX"
	ON "SKILL" ("NAME");

CREATE INDEX "AK_STAFF_NAME_IDX"
	ON "STAFF" ("FIRSTNAME","LASTNAME","BIRTH_DATE");

CREATE INDEX "AK_SUPPLIER_NAME_IDX"
	ON "SUPPLIER" ("NAME");

CREATE INDEX "Key1_IDX"
	ON "CONTRACT_SERVICE_AGREEMENT" ("CLIENT_ID","CONTRACT_ID","SERVICE_ID");

CREATE INDEX "PK_ASSIGNMENT_IDX"
	ON "ASSIGNMENT" ("ASSIGNMENT_ID");

CREATE INDEX "PK_ASSIGNMENT_ID_IDX"
	ON "STAFF_PROJECT_ASSIGNMENT" ("ASSIGNMENT_ID","PROJECT_ID","STAFF_ID","CLIENT_ID");

CREATE INDEX "PK_CITY_IDX"
	ON "CITY" ("CITY_ID","COUNTRY_ID");

CREATE INDEX "PK_CONTRACT_IDX"
	ON "CONTRACT" ("CLIENT_ID","CONTRACT_ID");

CREATE INDEX "PK_COUNTRY_ID_IDX"
	ON "COUNTRY" ("COUNTRY_ID");

CREATE INDEX "PK_COURSE_ID_IDX"
	ON "COURSE" ("COURSE_ID");

CREATE INDEX "PK_CUSTOMER_ID_IDX"
	ON "CLIENT" ("CLIENT_ID");

CREATE INDEX "PK_EMPLOYMENT_CONTRACT_IDX"
	ON "EMPLOYMENT_CONTRACT" ("EMPLOYMENT_CONTRACT_ID","STAFF_ID","SUPPLIER_ID");

CREATE INDEX "PK_ENROLLMENT_IDX"
	ON "ENROLMENT" ("COURSE_ID","STAFF_ID");

CREATE INDEX "PK_INTEREST_ID_IDX"
	ON "INTEREST" ("INTEREST_ID");

CREATE INDEX "PK_LOCATION_IDX"
	ON "LOCATION" ("CLIENT_ID","CITY_ID","COUNTRY_ID","PROJECT_ID");

CREATE INDEX "PK_PROJECT_IDX"
	ON "PROJECT" ("CLIENT_ID","PROJECT_ID");

CREATE INDEX "PK_SERVICE_ID_IDX"
	ON "SERVICE" ("SERVICE_ID");

CREATE INDEX "PK_SKILL_ID_IDX"
	ON "SKILL" ("SKILL_ID");

CREATE INDEX "PK_SKILL_USED_IDX"
	ON "STAFF_SKILL" ("STAFF_ID","SKILL_ID");

CREATE INDEX "PK_STAFF_ID_IDX"
	ON "STAFF" ("STAFF_ID");

CREATE INDEX "SUPPLIER_PK_IDX"
	ON "SUPPLIER" ("SUPPLIER_ID");

CREATE INDEX "SUPPLY_CONTRACT_PK_IDX"
	ON "SUPPLY_CONTRACT" ("SUPPLIER_ID","CLIENT_ID","CONTRACT_ID","STAFF_ID");

ALTER TABLE "ASSIGNMENT" ADD CONSTRAINT "AK_ASSIGNMENT" UNIQUE
	("DESC") USING INDEX "AK_ASSIGNMENT_IDX";

ALTER TABLE "ASSIGNMENT" ADD CONSTRAINT "PK_ASSIGNMENT" PRIMARY KEY
	("ASSIGNMENT_ID") USING INDEX "PK_ASSIGNMENT_IDX";

ALTER TABLE "CITY" ADD CONSTRAINT "AK_CITY_NAME" UNIQUE
	("NAME") USING INDEX "AK_CITY_NAME_IDX";

ALTER TABLE "CITY" ADD CONSTRAINT "PK_CITY" PRIMARY KEY
	("CITY_ID",
	 "COUNTRY_ID") USING INDEX "PK_CITY_IDX";

ALTER TABLE "CLIENT" ADD CONSTRAINT "AK_CLIENT" UNIQUE
	("NAME") USING INDEX "AK_CLIENT_IDX";

ALTER TABLE "CLIENT" ADD CONSTRAINT "PK_CUSTOMER_ID" PRIMARY KEY
	("CLIENT_ID") USING INDEX "PK_CUSTOMER_ID_IDX";

ALTER TABLE "CONTRACT" ADD CONSTRAINT "AK_CONTRACT_NAME" UNIQUE
	("NAME") USING INDEX "AK_CONTRACT_NAME_IDX";

ALTER TABLE "CONTRACT" ADD CONSTRAINT "PK_CONTRACT" PRIMARY KEY
	("CLIENT_ID",
	 "CONTRACT_ID") USING INDEX "PK_CONTRACT_IDX";

ALTER TABLE "CONTRACT_SERVICE_AGREEMENT" ADD CONSTRAINT "Key1" PRIMARY KEY
	("CLIENT_ID",
	 "CONTRACT_ID",
	 "SERVICE_ID") USING INDEX "Key1_IDX";

ALTER TABLE "COUNTRY" ADD CONSTRAINT "AK_COUNTRY_NAME" UNIQUE
	("NAME") USING INDEX "AK_COUNTRY_NAME_IDX";

ALTER TABLE "COUNTRY" ADD CONSTRAINT "PK_COUNTRY_ID" PRIMARY KEY
	("COUNTRY_ID") USING INDEX "PK_COUNTRY_ID_IDX";

ALTER TABLE "COURSE" ADD CONSTRAINT "AK_COURSE" UNIQUE
	("TITLE") USING INDEX "AK_COURSE_IDX";

ALTER TABLE "COURSE" ADD CONSTRAINT "PK_COURSE_ID" PRIMARY KEY
	("COURSE_ID") USING INDEX "PK_COURSE_ID_IDX";

ALTER TABLE "EMPLOYMENT_CONTRACT" ADD CONSTRAINT "PK_EMPLOYMENT_CONTRACT" PRIMARY KEY
	("EMPLOYMENT_CONTRACT_ID",
	 "STAFF_ID",
	 "SUPPLIER_ID") USING INDEX "PK_EMPLOYMENT_CONTRACT_IDX";

ALTER TABLE "ENROLMENT" ADD CONSTRAINT "PK_ENROLLMENT" PRIMARY KEY
	("COURSE_ID",
	 "STAFF_ID") USING INDEX "PK_ENROLLMENT_IDX";

ALTER TABLE "INTEREST" ADD CONSTRAINT "PK_INTEREST_ID" PRIMARY KEY
	("INTEREST_ID") USING INDEX "PK_INTEREST_ID_IDX";

ALTER TABLE "LOCATION" ADD CONSTRAINT "PK_LOCATION" PRIMARY KEY
	("CLIENT_ID",
	 "CITY_ID",
	 "COUNTRY_ID",
	 "PROJECT_ID") USING INDEX "PK_LOCATION_IDX";

ALTER TABLE "PROJECT" ADD CONSTRAINT "AK_PROJECT" UNIQUE
	("NAME",
	 "VERSION") USING INDEX "AK_PROJECT_IDX";

ALTER TABLE "PROJECT" ADD CONSTRAINT "PK_PROJECT" PRIMARY KEY
	("CLIENT_ID",
	 "PROJECT_ID") USING INDEX "PK_PROJECT_IDX";

ALTER TABLE "SERVICE" ADD CONSTRAINT "AK_SERVICE" UNIQUE
	("NAME") USING INDEX "AK_SERVICE_IDX";

ALTER TABLE "SERVICE" ADD CONSTRAINT "PK_SERVICE_ID" PRIMARY KEY
	("SERVICE_ID") USING INDEX "PK_SERVICE_ID_IDX";

ALTER TABLE "SKILL" ADD CONSTRAINT "AK_SKILL_NAME" UNIQUE
	("NAME") USING INDEX "AK_SKILL_NAME_IDX";

ALTER TABLE "SKILL" ADD CONSTRAINT "PK_SKILL_ID" PRIMARY KEY
	("SKILL_ID") USING INDEX "PK_SKILL_ID_IDX";

ALTER TABLE "STAFF" ADD CONSTRAINT "AK_STAFF_NAME" UNIQUE
	("FIRSTNAME",
	 "LASTNAME",
	 "BIRTH_DATE") USING INDEX "AK_STAFF_NAME_IDX";

ALTER TABLE "STAFF" ADD CONSTRAINT "PK_STAFF_ID" PRIMARY KEY
	("STAFF_ID") USING INDEX "PK_STAFF_ID_IDX";

ALTER TABLE "STAFF_PROJECT_ASSIGNMENT" ADD CONSTRAINT "PK_ASSIGNMENT_ID" PRIMARY KEY
	("ASSIGNMENT_ID",
	 "PROJECT_ID",
	 "STAFF_ID",
	 "CLIENT_ID") USING INDEX "PK_ASSIGNMENT_ID_IDX";

ALTER TABLE "STAFF_SKILL" ADD CONSTRAINT "PK_SKILL_USED" PRIMARY KEY
	("STAFF_ID",
	 "SKILL_ID") USING INDEX "PK_SKILL_USED_IDX";

ALTER TABLE "SUPPLIER" ADD CONSTRAINT "AK_SUPPLIER_NAME" UNIQUE
	("NAME") USING INDEX "AK_SUPPLIER_NAME_IDX";

ALTER TABLE "SUPPLIER" ADD CONSTRAINT "SUPPLIER_PK" PRIMARY KEY
	("SUPPLIER_ID") USING INDEX "SUPPLIER_PK_IDX";

ALTER TABLE "SUPPLY_CONTRACT" ADD CONSTRAINT "SUPPLY_CONTRACT_PK" PRIMARY KEY
	("SUPPLIER_ID",
	 "CLIENT_ID",
	 "CONTRACT_ID",
	 "STAFF_ID") USING INDEX "SUPPLY_CONTRACT_PK_IDX";

ALTER TABLE "CITY" ADD CONSTRAINT "HAS A" FOREIGN KEY
	("COUNTRY_ID")
	REFERENCES "COUNTRY"
	("COUNTRY_ID");

ALTER TABLE "CONTRACT" ADD CONSTRAINT "SIGNS" FOREIGN KEY
	("CLIENT_ID")
	REFERENCES "CLIENT"
	("CLIENT_ID");

ALTER TABLE "CONTRACT_SERVICE_AGREEMENT" ADD CONSTRAINT "ENGAGES" FOREIGN KEY
	("CLIENT_ID",
	 "CONTRACT_ID")
	REFERENCES "CONTRACT"
	("CLIENT_ID",
	 "CONTRACT_ID")
	ON DELETE CASCADE;

ALTER TABLE "CONTRACT_SERVICE_AGREEMENT" ADD CONSTRAINT "PROVIDES" FOREIGN KEY
	("SERVICE_ID")
	REFERENCES "SERVICE"
	("SERVICE_ID")
	ON DELETE CASCADE;

ALTER TABLE "EMPLOYMENT_CONTRACT" ADD CONSTRAINT "EMPLOYS" FOREIGN KEY
	("SUPPLIER_ID")
	REFERENCES "SUPPLIER"
	("SUPPLIER_ID")
	ON DELETE CASCADE;

ALTER TABLE "EMPLOYMENT_CONTRACT" ADD CONSTRAINT "IS EMPLOYED" FOREIGN KEY
	("STAFF_ID")
	REFERENCES "STAFF"
	("STAFF_ID")
	ON DELETE CASCADE;

ALTER TABLE "ENROLMENT" ADD CONSTRAINT "ENROLS" FOREIGN KEY
	("STAFF_ID")
	REFERENCES "STAFF"
	("STAFF_ID")
	ON DELETE CASCADE;

ALTER TABLE "ENROLMENT" ADD CONSTRAINT "IN" FOREIGN KEY
	("COURSE_ID")
	REFERENCES "COURSE"
	("COURSE_ID")
	ON DELETE CASCADE;

ALTER TABLE "INTEREST" ADD CONSTRAINT "HAS" FOREIGN KEY
	("STAFF_ID")
	REFERENCES "STAFF"
	("STAFF_ID")
	ON DELETE CASCADE;

ALTER TABLE "LOCATION" ADD CONSTRAINT "ESTABLISHES A" FOREIGN KEY
	("CITY_ID",
	 "COUNTRY_ID")
	REFERENCES "CITY"
	("CITY_ID",
	 "COUNTRY_ID")
	ON DELETE CASCADE;

ALTER TABLE "LOCATION" ADD CONSTRAINT "IS BASED" FOREIGN KEY
	("CLIENT_ID",
	 "PROJECT_ID")
	REFERENCES "PROJECT"
	("CLIENT_ID",
	 "PROJECT_ID")
	ON DELETE CASCADE;

ALTER TABLE "PROJECT" ADD CONSTRAINT "CONTROLS" FOREIGN KEY
	("CLIENT_ID")
	REFERENCES "CLIENT"
	("CLIENT_ID");

ALTER TABLE "STAFF_PROJECT_ASSIGNMENT" ADD CONSTRAINT "ASSIGNS" FOREIGN KEY
	("ASSIGNMENT_ID")
	REFERENCES "ASSIGNMENT"
	("ASSIGNMENT_ID")
	ON DELETE CASCADE;

ALTER TABLE "STAFF_PROJECT_ASSIGNMENT" ADD CONSTRAINT "IS COMPOSED OF" FOREIGN KEY
	("CLIENT_ID",
	 "PROJECT_ID")
	REFERENCES "PROJECT"
	("CLIENT_ID",
	 "PROJECT_ID")
	ON DELETE CASCADE;

ALTER TABLE "STAFF_PROJECT_ASSIGNMENT" ADD CONSTRAINT "WORKS ON" FOREIGN KEY
	("STAFF_ID")
	REFERENCES "STAFF"
	("STAFF_ID")
	ON DELETE CASCADE;

ALTER TABLE "STAFF_SKILL" ADD CONSTRAINT "IS USED" FOREIGN KEY
	("SKILL_ID")
	REFERENCES "SKILL"
	("SKILL_ID")
	ON DELETE CASCADE;

ALTER TABLE "STAFF_SKILL" ADD CONSTRAINT "USES" FOREIGN KEY
	("STAFF_ID")
	REFERENCES "STAFF"
	("STAFF_ID")
	ON DELETE CASCADE;

ALTER TABLE "SUPPLY_CONTRACT" ADD CONSTRAINT "AGREES" FOREIGN KEY
	("SUPPLIER_ID")
	REFERENCES "SUPPLIER"
	("SUPPLIER_ID")
	ON DELETE CASCADE;

ALTER TABLE "SUPPLY_CONTRACT" ADD CONSTRAINT "COMMITS TO" FOREIGN KEY
	("CLIENT_ID",
	 "CONTRACT_ID")
	REFERENCES "CONTRACT"
	("CLIENT_ID",
	 "CONTRACT_ID")
	ON DELETE CASCADE;

ALTER TABLE "SUPPLY_CONTRACT" ADD CONSTRAINT "WORKS IN" FOREIGN KEY
	("STAFF_ID")
	REFERENCES "STAFF"
	("STAFF_ID")
	ON DELETE CASCADE;

CREATE OR REPLACE VIEW "v_Experience" ("CONTRACT_ID", "FIRSTNAME", "LASTNAME", "ROLE", "CUSTOMER", "CITY", "COUNTRY") AS
SELECT CONTRACT.CONTRACT_ID, FIRSTNAME, LASTNAME, SERVICE.NAME AS ROLE, CLIENT.NAME AS CUSTOMER, CITY.NAME AS CITY, COUNTRY.NAME AS COUNTRY
FROM SERVICE, CLIENT, CONTRACT, STAFF, PROJECT, COUNTRY, CITY, LOCATION, STAFF_PROJECT_ASSIGNMENT, SUPPLIER, CONTRACT_SERVICE_AGREEMENT, EMPLOYMENT_CONTRACT, SUPPLY_CONTRACT
WHERE CITY.COUNTRY_ID = COUNTRY.COUNTRY_ID AND
LOCATION.CITY_ID = CITY.CITY_ID AND 
LOCATION.COUNTRY_ID = CITY.COUNTRY_ID AND 
LOCATION.PROJECT_ID = PROJECT.PROJECT_ID AND
PROJECT.CLIENT_ID = CLIENT.CLIENT_ID AND
CLIENT.CLIENT_ID = CONTRACT.CLIENT_ID AND
PROJECT.PROJECT_ID = STAFF_PROJECT_ASSIGNMENT.PROJECT_ID AND
PROJECT.CLIENT_ID = STAFF_PROJECT_ASSIGNMENT.CLIENT_ID AND
STAFF_PROJECT_ASSIGNMENT.STAFF_ID = STAFF.STAFF_ID AND
CONTRACT.CONTRACT_ID = CONTRACT_SERVICE_AGREEMENT.CONTRACT_ID AND
CONTRACT.CLIENT_ID  = CONTRACT_SERVICE_AGREEMENT.CLIENT_ID AND
CONTRACT_SERVICE_AGREEMENT.SERVICE_ID = SERVICE.SERVICE_ID  AND
CONTRACT.CONTRACT_ID = SUPPLY_CONTRACT.CONTRACT_ID AND
CONTRACT.CLIENT_ID = SUPPLY_CONTRACT.CLIENT_ID AND
SUPPLIER.SUPPLIER_ID = SUPPLY_CONTRACT.SUPPLIER_ID AND
SUPPLIER.SUPPLIER_ID = EMPLOYMENT_CONTRACT.SUPPLIER_ID AND
EMPLOYMENT_CONTRACT.STAFF_ID = STAFF.STAFF_ID
GROUP BY CONTRACT.CONTRACT_ID, FIRSTNAME, LASTNAME, SERVICE.NAME, CLIENT.NAME, CITY.NAME, COUNTRY.NAME;

CREATE OR REPLACE VIEW "v_ProjectTask" ("PROJECT_ID", "VERSION", "FIRSTNAME", "LASTNAME", "PROJECT", "PROJECT_VERSION", "TASK") AS
SELECT PROJECT.PROJECT_ID, VERSION, FIRSTNAME, LASTNAME, NAME AS PROJECT, VERSION AS PROJECT_VERSION, ASSIGNMENT.DESC AS TASK
FROM STAFF_PROJECT_ASSIGNMENT, PROJECT, STAFF, ASSIGNMENT
WHERE PROJECT.PROJECT_ID = STAFF_PROJECT_ASSIGNMENT.PROJECT_ID AND
PROJECT.CLIENT_ID = STAFF_PROJECT_ASSIGNMENT.CLIENT_ID AND
STAFF_PROJECT_ASSIGNMENT.ASSIGNMENT_ID = ASSIGNMENT.ASSIGNMENT_ID AND
STAFF.STAFF_ID = STAFF_PROJECT_ASSIGNMENT.STAFF_ID;

CREATE OR REPLACE VIEW "v_Resume" ("CONTRACT_ID", "CONTRACT", "FIRSTNAME", "LASTNAME", "ROLE", "CUSTOMER", "SUPPLIER", "CITY", "COUNTRY", "PROJECT", "RESPONSIBILITY", "START_DATE", "END_DATE") AS
SELECT CONTRACT.CONTRACT_ID, CONTRACT.NAME AS CONTRACT, FIRSTNAME, LASTNAME, SERVICE.NAME AS ROLE, CLIENT.NAME AS CUSTOMER, SUPPLIER.NAME AS SUPPLIER, CITY.NAME AS CITY, COUNTRY.NAME AS COUNTRY, PROJECT.NAME AS PROJECT, ASSIGNMENT.DESC AS RESPONSIBILITY, START_DATE, END_DATE
FROM CLIENT, COUNTRY, PROJECT, CONTRACT, STAFF_PROJECT_ASSIGNMENT, SERVICE, STAFF, CITY, SUPPLIER, LOCATION, ASSIGNMENT, CONTRACT_SERVICE_AGREEMENT, SUPPLY_CONTRACT
WHERE CITY.COUNTRY_ID                         = COUNTRY.COUNTRY_ID AND
LOCATION.CITY_ID                        = CITY.CITY_ID AND 
LOCATION.COUNTRY_ID                     = CITY.COUNTRY_ID AND 
LOCATION.PROJECT_ID                     = PROJECT.PROJECT_ID AND
PROJECT.CLIENT_ID                       = CLIENT.CLIENT_ID AND
CLIENT.CLIENT_ID                        = CONTRACT.CLIENT_ID AND
PROJECT.PROJECT_ID                      = STAFF_PROJECT_ASSIGNMENT.PROJECT_ID AND
PROJECT.CLIENT_ID                       = STAFF_PROJECT_ASSIGNMENT.CLIENT_ID AND
STAFF_PROJECT_ASSIGNMENT.STAFF_ID       = STAFF.STAFF_ID AND
CONTRACT.CONTRACT_ID                    = CONTRACT_SERVICE_AGREEMENT.CONTRACT_ID AND
CONTRACT.CLIENT_ID                      = CONTRACT_SERVICE_AGREEMENT.CLIENT_ID AND
CONTRACT_SERVICE_AGREEMENT.SERVICE_ID   = SERVICE.SERVICE_ID  AND
CONTRACT.CONTRACT_ID                    = SUPPLY_CONTRACT.CONTRACT_ID AND
CONTRACT.CLIENT_ID                      = SUPPLY_CONTRACT.CLIENT_ID AND
SUPPLIER.SUPPLIER_ID                    = SUPPLY_CONTRACT.SUPPLIER_ID AND
STAFF.STAFF_ID                          = SUPPLY_CONTRACT.STAFF_ID AND
ASSIGNMENT.ASSIGNMENT_ID                = STAFF_PROJECT_ASSIGNMENT.ASSIGNMENT_ID
GROUP BY CONTRACT.CONTRACT_ID, CONTRACT.NAME, FIRSTNAME, LASTNAME, SERVICE.NAME, CLIENT.NAME, CITY.NAME, COUNTRY.NAME, PROJECT.NAME, ASSIGNMENT.DESC, SUPPLIER.NAME, START_DATE, END_DATE;

