SELECT "CONTRACT"."CONTRACT_ID", "CONTRACT"."NAME" AS "CONTRACT", "FIRSTNAME", "LASTNAME", "SERVICE"."NAME" AS "ROLE", "CLIENT"."NAME" AS "CUSTOMER", "SUPPLIER"."NAME" AS "SUPPLIER", "CITY"."NAME" AS "CITY", "COUNTRY"."NAME" AS "COUNTRY", "PROJECT"."NAME" AS "PROJECT", "TASK"."DESC" AS "TASK", "START_DATE", "END_DATE",  "PROJECT"."PROJECT_ID",  "PROJECT"."VERSION", "CLIENT"."NAME",CLIENT.CLIENT_ID
FROM "CLIENT", "COUNTRY", "PROJECT", "CONTRACT", "ASSIGNMENT", "SERVICE", "STAFF", "CITY", "SUPPLIER", "LOCATION", "TASK", "AGREEMENT", "SUPPLY_CONTRACT"
WHERE CITY.COUNTRY_ID                         = COUNTRY.COUNTRY_ID AND
        LOCATION.CITY_ID                        = CITY.CITY_ID AND
        LOCATION.COUNTRY_ID                     = CITY.COUNTRY_ID AND
        LOCATION.PROJECT_ID                     = PROJECT.PROJECT_ID AND
        PROJECT.CLIENT_ID                       = CLIENT.CLIENT_ID AND
        CLIENT.CLIENT_ID                        = CONTRACT.CLIENT_ID AND
        PROJECT.PROJECT_ID                      = ASSIGNMENT.PROJECT_ID AND
        PROJECT.CLIENT_ID                       = ASSIGNMENT.CLIENT_ID AND
        ASSIGNMENT.STAFF_ID       			= STAFF.STAFF_ID AND
        CONTRACT.CONTRACT_ID                    = AGREEMENT.CONTRACT_ID AND
        CONTRACT.CLIENT_ID                      = AGREEMENT.CLIENT_ID AND
        AGREEMENT.SERVICE_ID   			= SERVICE.SERVICE_ID  AND
        CONTRACT.CONTRACT_ID                    = SUPPLY_CONTRACT.CONTRACT_ID AND
        CONTRACT.CLIENT_ID                      = SUPPLY_CONTRACT.CLIENT_ID AND
        SUPPLIER.SUPPLIER_ID                    = SUPPLY_CONTRACT.SUPPLIER_ID AND
        STAFF.STAFF_ID                          = SUPPLY_CONTRACT.STAFF_ID AND
        TASK.TASK_ID               				 = ASSIGNMENT.TASK_ID AND
        CITY.NAME = 'London'
GROUP BY "CONTRACT"."CONTRACT_ID", "CONTRACT"."NAME", "FIRSTNAME", "LASTNAME", "SERVICE"."NAME", "CLIENT"."NAME", "CITY"."NAME", "COUNTRY"."NAME", "PROJECT"."NAME", "TASK"."DESC", "SUPPLIER"."NAME", "START_DATE", "END_DATE", "PROJECT"."PROJECT_ID";

--Insert date
insert into SUPPLY_CONTRACT (END_DATE, START_DATE, CLIENT_ID, CONTRACT_ID, STAFF_ID, SUPPLIER_ID) values ('2023-08-01', '2023-08-01', 12, 13, 2, 1);